# actions tests the code with different node LTS versions
name: npm-test-node-versions
on: push

jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14', '16' ]
    name: Node ${{ matrix.node }} test run
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test

